"""Add time_required and time_to_sell columns to Project

Revision ID: 7bfa9fd8d2bb
Revises: f46d6ee4860a
Create Date: 2024-05-24 22:44:46.660921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfa9fd8d2bb'
down_revision = 'f46d6ee4860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_required', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time_required_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('time_to_sell', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time_to_sell_unit', sa.String(length=20), nullable=True))
        batch_op.drop_column('time')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_sell_unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('time_to_sell_unit')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('time_to_sell_unit')
        batch_op.drop_column('time_to_sell')
        batch_op.drop_column('time_required_unit')
        batch_op.drop_column('time_required')

    # ### end Alembic commands ###
