"""Add new fields to Project model

Revision ID: 803dbb0e755e
Revises: ecf23e712155
Create Date: 2024-05-24 15:34:53.346595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803dbb0e755e'
down_revision = 'ecf23e712155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('resources')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('protections')
        batch_op.drop_column('funding')
        batch_op.drop_column('protocol')
        batch_op.drop_column('alignment')
        batch_op.drop_column('goal')
        batch_op.drop_column('urgency')
        batch_op.drop_column('materials')
        batch_op.drop_column('principle')
        batch_op.drop_column('consumables')
        batch_op.drop_column('impact')
        batch_op.drop_column('complexity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complexity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('principle', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('materials', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('alignment', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('funding', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('protections', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('prerequisites', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
