"""Initial migration

Revision ID: a552d1b941cd
Revises: 
Create Date: 2024-07-12 21:10:17.714487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a552d1b941cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('funds',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('materials',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('projects',
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('resources', sa.Float(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('alignment', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('principle', sa.Text(), nullable=True),
    sa.Column('protocol_text', sa.Text(), nullable=True),
    sa.Column('time_required', sa.Float(), nullable=True),
    sa.Column('time_required_unit', sa.String(length=20), nullable=True),
    sa.Column('funding', sa.Float(), nullable=True),
    sa.Column('benefits', sa.Float(), nullable=True),
    sa.Column('time_to_sell', sa.Float(), nullable=True),
    sa.Column('time_to_sell_unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('protections',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('project_consumable_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'consumable_id')
    )
    op.create_table('project_material_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'material_id')
    )
    op.create_table('project_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_project_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'prerequisite_project_id')
    )
    op.create_table('project_protection_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('protection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['protection_id'], ['protections.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'protection_id')
    )
    op.create_table('project_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocols',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('principle', sa.Text(), nullable=True),
    sa.Column('protocol_text', sa.Text(), nullable=True),
    sa.Column('time_required', sa.Float(), nullable=True),
    sa.Column('time_required_unit', sa.String(length=20), nullable=True),
    sa.Column('funding', sa.Float(), nullable=True),
    sa.Column('benefits', sa.Float(), nullable=True),
    sa.Column('time_to_sell', sa.Float(), nullable=True),
    sa.Column('time_to_sell_unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('protocol_consumable_association',
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('consumable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], )
    )
    op.create_table('protocol_material_association',
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], )
    )
    op.create_table('protocol_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_protection_association',
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('protection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protection_id'], ['protections.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], )
    )
    op.create_table('protocol_protocol_association',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_protocol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('protocol_id', 'prerequisite_protocol_id')
    )
    op.create_table('protocol_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('resources', sa.Float(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('alignment', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_daily', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('principle', sa.Text(), nullable=True),
    sa.Column('protocol_text', sa.Text(), nullable=True),
    sa.Column('time_required', sa.Float(), nullable=True),
    sa.Column('time_required_unit', sa.String(length=20), nullable=True),
    sa.Column('funding', sa.Float(), nullable=True),
    sa.Column('benefits', sa.Float(), nullable=True),
    sa.Column('time_to_sell', sa.Float(), nullable=True),
    sa.Column('time_to_sell_unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('task_consumable_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'consumable_id')
    )
    op.create_table('task_material_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'material_id')
    )
    op.create_table('task_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_protection_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('protection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protection_id'], ['protections.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'protection_id')
    )
    op.create_table('task_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_task_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'prerequisite_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_task_association')
    op.drop_table('task_resources')
    op.drop_table('task_protection_association')
    op.drop_table('task_prerequisites')
    op.drop_table('task_material_association')
    op.drop_table('task_consumable_association')
    op.drop_table('tasks')
    op.drop_table('protocol_resources')
    op.drop_table('protocol_protocol_association')
    op.drop_table('protocol_protection_association')
    op.drop_table('protocol_prerequisites')
    op.drop_table('protocol_material_association')
    op.drop_table('protocol_consumable_association')
    op.drop_table('protocols')
    op.drop_table('project_resources')
    op.drop_table('project_protection_association')
    op.drop_table('project_project_association')
    op.drop_table('project_prerequisites')
    op.drop_table('project_material_association')
    op.drop_table('project_consumable_association')
    op.drop_table('protections')
    op.drop_table('projects')
    op.drop_table('materials')
    op.drop_table('funds')
    op.drop_table('consumables')
    # ### end Alembic commands ###
