"""Rename relationship backref

Revision ID: b07fdfb63790
Revises: 7bfa9fd8d2bb
Create Date: 2024-05-24 22:47:01.145879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07fdfb63790'
down_revision = '7bfa9fd8d2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_required_unit', sa.String(length=20), nullable=True))
        batch_op.drop_column('time_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_unit', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('time_required_unit')

    # ### end Alembic commands ###
