"""Add new fields to Project model

Revision ID: ed2460bc8014
Revises: 803dbb0e755e
Create Date: 2024-05-24 15:39:07.905475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2460bc8014'
down_revision = '803dbb0e755e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('principle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prerequisites', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('protections', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('materials', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('funding', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('complexity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alignment', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('alignment')
        batch_op.drop_column('complexity')
        batch_op.drop_column('resources')
        batch_op.drop_column('impact')
        batch_op.drop_column('urgency')
        batch_op.drop_column('funding')
        batch_op.drop_column('time')
        batch_op.drop_column('consumables')
        batch_op.drop_column('materials')
        batch_op.drop_column('protections')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('protocol')
        batch_op.drop_column('principle')
        batch_op.drop_column('goal')

    # ### end Alembic commands ###
